### ISSUE TITLE
Create Icon for Katz Team

### ISSUE THREAD

**Issue by nguyenphuc22** [Katz-Team/CalRent#2]
Let's create an Icon that represents the word "Katz", you can be as creative as you like

**Comment by r0yaL-tWo** [comment]
![IMG_20231005_095819.jpg](https://github.com/Katz-Team/CalRent/assets/75350542/49d17b11-fd95-4da1-b29b-e3639ad256ed)

**Comment by nguyenphuc22** [comment]
@r0yaL-tWo  Please! Close this issue
